name: GitHub Actions Test

on:
  push:
    branches: [ "main", "Development" ]
  pull_request:
    branches: [ "main", "Development" ]
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install
        working-directory: worksheet4/frontend

      - name: Run test
        run: npm run lint
        working-directory: worksheet4/frontend
